#!/bin/sh
# SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note
#
# Copyright (c) 2026, Oracle and/or its affiliates.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public
# License v2 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

. $PCP_DIR/etc/pcp.env
. $PCP_SHARE_DIR/lib/pmdaproc.sh

iam=dtrace
domain=487
pmda_interface=2
# Extend PMNS with the shipped namespace fragment
pmns_update=true
pmnsfile=$iam
python_user=root
python_group=root
python_opt=true
daemon_opt=false

ipc_prot="binary notready"

pmdaSetup
pmdaInstall -U root
exit
